# Enhanced YOLO Dataset Config
nc: 10
names: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
train: /home/ngoductam/KLGrade/processed/enhanced/splits/knee_10_class/yolo11l_E_ENHANCED_004_knee10_full/train.txt
val: /home/ngoductam/KLGrade/processed/enhanced/splits/knee_10_class/yolo11l_E_ENHANCED_004_knee10_full/val.txt
test: /home/ngoductam/KLGrade/processed/enhanced/splits/knee_10_class/yolo11l_E_ENHANCED_004_knee10_full/test.txt
